name: "test"

on: [push]

jobs:

  # Trivy:
  #   name: Trivy
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Run Trivy vulnerability scanner in IaC mode
  #       uses: aquasecurity/trivy-action@0.28.0
  #       with:
  #         scan-type: 'config'
  #         hide-progress: true
  #         format: 'sarif'
  #         output: 'trivy-results.sarif'
  #         exit-code: '0'
  #         severity: 'CRITICAL,HIGH,MEDIUM,LOW'

  #     - name: Upload Trivy scan results to GitHub Security tab
  #       uses: github/codeql-action/upload-sarif@v3
  #       with:
  #         sarif_file: 'trivy-results.sarif'

  Semgrep:
    name: Semgrep
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Semgrep
        run: python3 -m pip install --upgrade requests && python3 -m pip install semgrep

      - name: Run Semgrep in default mode
        run: semgrep scan >> semgrep-scan.txt

      - name: Upload Semgrep Scan Report
        uses: actions/upload-artifact@v4
        with:
          name: Semgrep Scan Report
          path: semgrep-scan.txt
